---
language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
install:
  - cpanm  --quiet  --notest --skip-satisfied Dist::Zilla
  - dzil authordeps | cpanm  --quiet   --notest  --skip-satisfied
  - dzil listdeps --author | cpanm  --quiet   --notest  --skip-satisfied
script:
  - dzil smoke --release --author
